"""
Renderer Service — Autonomous Content Bridge
Uses FFmpeg to burn subtitles into video and optimize for Twitter.
"""
import asyncio
import logging
import os
from pathlib import Path

from backend.config import get_settings

logger = logging.getLogger("content-bridge.renderer")

# Twitter video limits
TWITTER_MAX_DURATION = 140  # seconds
TWITTER_MAX_SIZE_MB = 512


async def render_video(
    video_path: str,
    subtitle_path: str,
    job_id: int,
    optimize_for_twitter: bool = True,
    ocr_filters: list[str] = None,
) -> str:
    """
    Burn subtitles into video using FFmpeg.

    Args:
        video_path: Source video file
        subtitle_path: .srt or .ass subtitle file
        job_id: Job identifier
        optimize_for_twitter: If True, enforce Twitter limits
        ocr_filters: Optional list of FFmpeg filter strings generated by OCR to blur/replace text

    Returns:
        Path to the rendered output video
    """
    settings = get_settings()
    output_dir = settings.processed_dir / str(job_id)
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = str(output_dir / "output.mp4")

    logger.info(f"[Job {job_id}] Rendering video with subtitles...")

    # Determine subtitle filter based on file extension
    sub_ext = Path(subtitle_path).suffix.lower()
    if sub_ext == ".ass":
        # Add a semi-transparent black band at the bottom to mask hardcoded subtitles
        mask_filter = "drawbox=y=ih-ih*0.18:color=black@0.75:width=iw:height=ih*0.18:t=fill"
        # ASS uses the ass filter for styled subtitles
        sub_filter = f"{mask_filter},ass='{subtitle_path}'"
    else:
        # SRT uses the subtitles filter
        sub_filter = f"subtitles='{subtitle_path}':force_style='FontSize=24,PrimaryColour=&H00FFFFFF,OutlineColour=&H00000000,Outline=2,Shadow=0,MarginV=40'"

    # Inject OCR filters if available
    if ocr_filters:
        ocr_chain = ",".join(ocr_filters)
        sub_filter = f"{ocr_chain},{sub_filter}"

    # Build FFmpeg command
    cmd = [
        "ffmpeg", "-y",
        "-i", video_path,
        "-vf", sub_filter,
        "-c:v", "libx264",
        "-preset", "fast",       # Balance speed vs quality
        "-crf", "23",            # Good quality
        "-c:a", "aac",
        "-b:a", "128k",
        "-movflags", "+faststart",  # Web-optimized MP4
    ]

    if optimize_for_twitter:
        # Get video duration first
        duration = await _get_duration(video_path)
        if duration and duration > TWITTER_MAX_DURATION:
            logger.warning(
                f"[Job {job_id}] Video too long for Twitter ({duration}s > {TWITTER_MAX_DURATION}s). "
                f"Trimming to {TWITTER_MAX_DURATION}s."
            )
            cmd.extend(["-t", str(TWITTER_MAX_DURATION)])

        # Limit resolution and bitrate for file size
        cmd.extend([
            "-vf", f"scale='min(1280,iw)':-2,{sub_filter.split('=', 1)[0]}={sub_filter.split('=', 1)[1]}",
            "-maxrate", "5M",
            "-bufsize", "10M",
        ])
        # Replace the double -vf with combined filter
        # Rebuild cmd properly
        cmd = [
            "ffmpeg", "-y",
            "-i", video_path,
            "-vf", f"scale='min(1280,iw)':-2,{sub_filter}",
            "-c:v", "libx264",
            "-preset", "fast",
            "-crf", "23",
            "-c:a", "aac",
            "-b:a", "128k",
            "-maxrate", "5M",
            "-bufsize", "10M",
            "-movflags", "+faststart",
        ]

        if duration and duration > TWITTER_MAX_DURATION:
            cmd.extend(["-t", str(TWITTER_MAX_DURATION)])

    cmd.append(output_path)

    logger.info(f"[Job {job_id}] FFmpeg command: {' '.join(cmd)}")

    process = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    _, stderr = await process.communicate()

    if process.returncode != 0:
        error = stderr.decode("utf-8", errors="replace")
        logger.error(f"[Job {job_id}] FFmpeg render failed: {error[-500:]}")
        raise RuntimeError(f"Video rendering failed: {error[-500:]}")

    # Check output file
    output_size_mb = os.path.getsize(output_path) / (1024 * 1024)
    logger.info(
        f"[Job {job_id}] Render complete: {output_path} ({output_size_mb:.1f} MB)"
    )

    if optimize_for_twitter and output_size_mb > TWITTER_MAX_SIZE_MB:
        logger.warning(
            f"[Job {job_id}] Output too large for Twitter ({output_size_mb:.1f}MB). "
            f"Re-encoding with lower quality..."
        )
        output_path = await _reencode_smaller(video_path, subtitle_path, job_id, sub_filter)

    return output_path


async def _get_duration(video_path: str) -> float | None:
    """Get video duration in seconds using ffprobe."""
    cmd = [
        "ffprobe",
        "-v", "error",
        "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1",
        video_path,
    ]
    process = await asyncio.create_subprocess_exec(
        *cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE
    )
    stdout, _ = await process.communicate()
    try:
        return float(stdout.decode().strip())
    except (ValueError, AttributeError):
        return None


async def _reencode_smaller(
    video_path: str, subtitle_path: str, job_id: int, sub_filter: str
) -> str:
    """Re-encode with lower quality to fit Twitter size limit."""
    settings = get_settings()
    output_path = str(settings.processed_dir / str(job_id) / "output_compressed.mp4")

    cmd = [
        "ffmpeg", "-y",
        "-i", video_path,
        "-vf", f"scale='min(720,iw)':-2,{sub_filter}",
        "-c:v", "libx264",
        "-preset", "medium",
        "-crf", "28",
        "-c:a", "aac",
        "-b:a", "96k",
        "-maxrate", "2M",
        "-bufsize", "4M",
        "-t", str(TWITTER_MAX_DURATION),
        "-movflags", "+faststart",
        output_path,
    ]

    process = await asyncio.create_subprocess_exec(
        *cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE
    )
    _, stderr = await process.communicate()

    if process.returncode != 0:
        error = stderr.decode("utf-8", errors="replace")
        raise RuntimeError(f"Re-encode failed: {error[-500:]}")

    logger.info(f"[Job {job_id}] Re-encoded to smaller size: {output_path}")
    return output_path
